# frozen_string_literal: true

# PLC コードジェネレータ
# 解析済み IREP から KV スクリプト用のメモリ初期化コードを生成します。

require_relative "mrb_parser"
require_relative "vm_constants"
require_relative "memory_layout"
require "plc_access"

module FaRuby
  # 生成対象がメモリ配置に収まらない場合に発生
  class CodegenError < StandardError; end

  class PlcCodegen
    include VmConstants

    attr_reader :layout

    def initialize(irep, steps_per_cycle: 50, layout: MemoryLayout.default)
      @irep = irep
      @steps_per_cycle = steps_per_cycle
      @layout = layout
    end

    # 各領域が上限を超えていないか検証する
    # 超えたまま生成すると隣接領域 (定数プール → デバイステーブル等) を
    # 破壊するため、生成前に必ず呼ぶ。
    def validate!
      check_limit("レジスタ数", @irep.nregs, layout.max_regs)
      check_limit("バイトコード長", @irep.ilen, layout.max_bytecode)
      check_limit("定数プールのエントリ数", @irep.pool.size, layout.max_pool)
      check_limit("シンボル数", @irep.symbols.size, layout.max_symbols)
      check_unsupported_access
      self
    end

    # EM レジスタ初期化用の KV スクリプトを生成
    def generate
      validate!
      lines = []
      lines << "' ======================================="
      lines << "' faRuby VM - Memory Initialization"
      lines << "' Generated by faRuby plc_codegen.rb"
      lines << "' ======================================="
      lines << ""

      lines.concat(generate_vm_state)
      lines << ""
      lines.concat(generate_bytecode)
      lines << ""
      lines.concat(generate_pool)
      lines << ""
      lines.concat(generate_device_table)

      lines.join("\n")
    end

    # メモリイメージを Hash として返す (シミュレータ用)
    # { address => value, ... }
    def memory_image
      validate!
      image = {}

      # VM 状態
      image[layout.pc_addr] = 0
      image[layout.status_addr] = VM_RUNNING
      image[layout.error_addr] = 0
      image[layout.step_count_addr] = 0
      image[layout.step_count_addr + 1] = 0
      image[layout.steps_per_cycle_addr] = @steps_per_cycle
      image[layout.bytecode_len_addr] = @irep.ilen
      image[layout.nregs_addr] = @irep.nregs
      image[layout.nlocals_addr] = @irep.nlocals

      # バイトコード
      @irep.instructions.each_byte.each_with_index do |b, i|
        image[layout.bytecode_base + i] = b
      end

      # 定数プール (値スロット: 型タグ + 32ビット値)
      #
      # 未対応の型はスロットを 0 (TT_EMPTY) で埋める。OP_LOADL はタグごと
      # 複製するため、書かずに残すと不定のタグを拾ってしまう。
      @irep.pool.each_with_index do |entry, i|
        value = pool_slot_value(entry)
        addr = layout.pool_addr(i)
        image[layout.pool_type_addr(i)] = value ? pool_type_tag(entry) : TT_EMPTY
        image[addr]     = value ? value & 0xFFFF : 0
        image[addr + 1] = value ? (value >> 16) & 0xFFFF : 0
      end

      # レジスタファイル初期化 (スロット全体を 0 = TT_EMPTY + 値 0)
      @irep.nregs.times do |i|
        slot = layout.reg_slot_addr(i)
        SLOT_WORDS.times { |w| image[slot + w] = 0 }
      end

      # デバイスマッピングテーブル
      image[layout.num_symbols_addr] = @irep.symbols.size
      device_mappings.each do |m|
        image[m[:table_addr]]     = m[:device_type]
        image[m[:table_addr] + 1] = m[:z_offset]
        image[m[:table_addr] + 2] = m[:access_type] || 0
        image[m[:table_addr] + 3] = 0
        # 汎用グローバルはスロット全体を 0 初期化
        next unless m[:general]

        slot = m[:z_offset] - SLOT_VALUE_OFFSET
        SLOT_WORDS.times { |w| image[slot + w] = 0 }
      end

      image
    end

    # シンボルごとのデバイス割り当てを解決する
    # デバイス名にマッチするシンボル ($DM100 等) は該当デバイスへ、
    # マッチしないシンボル ($foo 等) は汎用グローバル領域へ出現順に割り当てる。
    # z_offset は「値ワード」のアドレス (デバイスマッピングテーブルに格納する値)。
    def device_mappings
      slot_index = 0
      @irep.symbols.each_with_index.map do |sym, idx|
        table_addr = layout.device_table_base + idx * DEVICE_TABLE_STRIDE
        parsed = parse_device_symbol(sym)
        if parsed
          { symbol: sym, index: idx, table_addr: table_addr, general: false,
            device_type: parsed[:device_type], device_name: parsed[:device_name],
            address: parsed[:address], z_offset: parsed[:z_offset],
            access_type: parsed[:access_type], bit: parsed[:bit] }
        else
          # 汎用グローバル変数は Ruby の値を保持するので常に32ビット
          value_addr = layout.general_global_addr(slot_index)
          slot_index += 1
          { symbol: sym, index: idx, table_addr: table_addr, general: true,
            device_type: DEVICE_TYPE_EM, device_name: layout.device_name,
            address: value_addr.to_s, z_offset: value_addr,
            access_type: ACCESS_L, bit: false }
        end
      end
    end

    private

    def check_limit(label, actual, limit)
      return if actual <= limit

      raise CodegenError, "#{label}が上限を超えています (#{actual} > #{limit})"
    end

    # 実数 (F サフィックス) は VM が型タグを扱えるようになるまで未対応
    def check_unsupported_access
      floats = device_mappings.select { |m| m[:access_type] == ACCESS_F }
      return if floats.empty?

      names = floats.map { |m| m[:symbol] }.join(", ")
      raise CodegenError,
            "実数デバイス (F サフィックス) は未実装です: #{names} " \
            "(VM の型タグ実装が必要。整数は S/U/L/D が使えます)"
    end

    # プールエントリの型タグを返す
    def pool_type_tag(entry)
      case entry.type
      when :int32, :int64 then TT_INTEGER
      when :float         then TT_FLOAT
      else                     TT_EMPTY
      end
    end

    # プールエントリの 32ビット値を返す (未対応の型は nil)
    def pool_slot_value(entry)
      case entry.type
      when :int32 then entry.value
      when :int64 then entry.value & 0xFFFFFFFF  # 下位32ビットのみ使用
      end
    end

    def generate_vm_state
      lines = []
      lines << "' --- VM State ---"
      lines << "#{layout.device(layout.pc_addr)} = 0           ' PC = 0"
      lines << "#{layout.device(layout.status_addr)} = #{VM_RUNNING}           ' STATUS = running"
      lines << "#{layout.device(layout.error_addr)} = 0           ' ERROR = none"
      lines << "#{layout.device_long(layout.step_count_addr)} = 0     ' STEP_COUNT = 0"
      lines << "#{layout.device(layout.steps_per_cycle_addr)} = #{@steps_per_cycle}          ' STEPS_PER_CYCLE"
      lines << "#{layout.device(layout.bytecode_len_addr)} = #{@irep.ilen}         ' BYTECODE_LEN"
      lines << "#{layout.device(layout.nregs_addr)} = #{@irep.nregs}          ' NREGS"
      lines << "#{layout.device(layout.nlocals_addr)} = #{@irep.nlocals}          ' NLOCALS"
      lines << "#{layout.device(layout.reset_req_addr)} = 0          ' RESET_REQ = off"
      lines << ""
      lines << "' --- Clear Register File (#{SLOT_WORDS} words/slot) ---"
      lines << "FOR Z1 = #{layout.reg_file_base} TO #{layout.reg_slot_addr(@irep.nregs) - 1}"
      lines << "    #{layout.device_name}0:Z1 = 0"
      lines << "NEXT"
      lines
    end

    def generate_bytecode
      lines = []
      lines << "' --- Bytecode (#{@irep.ilen} bytes) ---"

      @irep.instructions.each_byte.each_with_index do |b, i|
        lines << "#{layout.device(layout.bytecode_base + i)} = #{b}"
      end

      lines
    end

    def generate_pool
      return [] if @irep.pool.empty?

      lines = []
      lines << "' --- Constant Pool (#{@irep.pool.size} entries) ---"

      @irep.pool.each_with_index do |entry, i|
        case entry.type
        when :int32, :int64
          lines << "#{layout.device(layout.pool_type_addr(i))} = #{TT_INTEGER}    ' Pool[#{i}] type=integer"
          lines << "#{layout.device_long(layout.pool_addr(i))} = #{entry.value}    ' Pool[#{i}]"
        when :float
          lines << "' Pool[#{i}] = #{entry.value} (float - not supported in milestone 1)"
        else
          lines << "' Pool[#{i}] = #{entry} (type #{entry.type} - not supported)"
        end
      end

      lines
    end

    def generate_device_table
      return [] if @irep.symbols.empty?

      lines = []
      lines << "' --- Device Mapping Table (#{@irep.symbols.size} symbols) ---"
      lines << "#{layout.device(layout.num_symbols_addr)} = #{@irep.symbols.size}    ' NUM_SYMBOLS"

      mappings = device_mappings
      mappings.each do |m|
        table_addr = m[:table_addr]
        kind = m[:bit] ? "ビット" : ACCESS_NAMES[m[:access_type]]
        if m[:general]
          lines << "#{layout.device(table_addr)} = #{DEVICE_TYPE_EM}    ' #{m[:symbol]} type=EM (auto)"
          lines << "#{layout.device(table_addr + 1)} = #{m[:z_offset]}    ' #{m[:symbol]} -> #{layout.device(m[:z_offset])}"
        else
          lines << "#{layout.device(table_addr)} = #{m[:device_type]}    ' #{m[:symbol]} type=#{DEVICE_TYPE_NAMES[m[:device_type]]}"
          lines << "#{layout.device(table_addr + 1)} = #{m[:z_offset]}    ' #{m[:symbol]} Z offset"
        end
        lines << "#{layout.device(table_addr + 2)} = #{m[:access_type] || 0}    ' #{m[:symbol]} access=#{kind}"
        lines << "#{layout.device(table_addr + 3)} = 0    ' #{m[:symbol]} 予備"
      end

      lines.concat(generate_general_global_clear(mappings))
      lines
    end

    # 汎用グローバル変数のスロットを 0 初期化する
    # (memory_image と同じ初期化を KV スクリプト側でも行う)
    def generate_general_global_clear(mappings)
      general = mappings.select { |m| m[:general] }
      return [] if general.empty?

      # 汎用グローバルは汎用グローバル領域の先頭から連続して割り当てられる
      first = general.first[:z_offset] - SLOT_VALUE_OFFSET
      last  = general.last[:z_offset] - SLOT_VALUE_OFFSET + SLOT_WORDS - 1

      ["",
       "' --- Clear General Globals (#{general.size} slots × #{SLOT_WORDS} words) ---",
       "FOR Z1 = #{first} TO #{last}",
       "    EM0:Z1 = 0",
       "NEXT"]
    end

    # ワードデバイス: 10進アドレス + アクセス幅サフィックス (省略時は16ビット符号付き)
    #   $DM100 / $DM100S / $DM100U / $DM100L / $DM100D / $DM100F
    WORD_DEVICE_PATTERN      = /^\$(EM|DM|ZF)(\d+)([SULDF]?)$/i
    WORD_DEVICE_PATTERN_BARE = /^(EM|DM|ZF)(\d+)([SULDF]?)$/i

    # ビットデバイス: 幅の概念が無いためサフィックス無し
    # MR を R より先にマッチさせる。B は16進アドレス (例: $B1F)、他は10進
    # CR はインデックス扱い不可のため非対応
    BIT_DEVICE_PATTERN      = /^\$(MR|R|B|L|T|C)([0-9A-Fa-f]+)$/i
    BIT_DEVICE_PATTERN_BARE = /^(MR|R|B|L|T|C)([0-9A-Fa-f]+)$/i
    DEVICE_NAME_TO_TYPE = {
      "EM" => DEVICE_TYPE_EM, "DM" => DEVICE_TYPE_DM, "ZF" => DEVICE_TYPE_ZF,
      "R" => DEVICE_TYPE_R, "MR" => DEVICE_TYPE_MR, "B" => DEVICE_TYPE_B,
      "L" => DEVICE_TYPE_L, "T" => DEVICE_TYPE_T, "C" => DEVICE_TYPE_C,
    }.freeze
    DEVICE_TYPE_NAMES = DEVICE_NAME_TO_TYPE.invert.freeze

    # KvDevice を使ってデバイスアドレスの Z レジスタ用オフセットを取得
    # HEXDEC (R, MR 等): MR200 → 32, R100 → 16
    # HEX (B): B10 → 16
    # DEC (EM, DM 等): そのまま
    def self.device_z_offset(device_name, addr_str)
      PlcAccess::Protocol::Keyence::KvDevice.new("#{device_name}#{addr_str}").number
    end

    def parse_device_symbol(sym)
      self.class.parse_device_symbol(sym)
    end

    # シンボル名 ($DM100, $DM100L) からデバイス情報をパース
    # address:     元のアドレス (PLC アダプタ通信用)
    # z_offset:    Z レジスタ用オフセット (マッピングテーブル・シミュレータ用)
    # access_type: ACCESS_* (ビットデバイスは nil)
    def self.parse_device_symbol(sym)
      parse_device(sym, WORD_DEVICE_PATTERN, BIT_DEVICE_PATTERN)
    end

    # デバイス名 (DM100, DM100L, $ なし) からデバイス情報をパース
    def self.parse_device_name(name)
      parse_device(name, WORD_DEVICE_PATTERN_BARE, BIT_DEVICE_PATTERN_BARE)
    end

    # ワードデバイス → ビットデバイスの順にマッチを試みる
    def self.parse_device(str, word_pattern, bit_pattern)
      return nil unless str

      if (m = str.match(word_pattern))
        device_name = m[1].upcase
        addr_str = m[2]
        access_type = VmConstants::ACCESS_SUFFIXES.fetch(m[3].to_s.upcase)
        return { device_type: DEVICE_NAME_TO_TYPE[device_name], address: addr_str,
                 z_offset: device_z_offset(device_name, addr_str),
                 device_name: device_name, access_type: access_type, bit: false }
      end

      return nil unless (m = str.match(bit_pattern))

      device_name = m[1].upcase
      addr_str = m[2]
      { device_type: DEVICE_NAME_TO_TYPE[device_name], address: addr_str,
        z_offset: device_z_offset(device_name, addr_str),
        device_name: device_name, access_type: nil, bit: true }
    end
  end
end

# コマンドラインから実行した場合
if __FILE__ == $0
  require_relative "mrb_parser"

  if ARGV.empty?
    puts "Usage: ruby plc_codegen.rb <file.mrb>"
    exit 1
  end

  data = File.binread(ARGV[0])
  parser = FaRuby::MrbParser.new(data).parse
  codegen = FaRuby::PlcCodegen.new(parser.irep)
  puts codegen.generate
end
