# frozen_string_literal: true

# PLC コードジェネレータ
# 解析済み IREP から KV スクリプト用のメモリ初期化コードを生成します。

require_relative "mrb_parser"
require_relative "memory_map"

module RubyOnPlc
  class PlcCodegen
    include MemoryMap

    def initialize(irep, steps_per_cycle: 50)
      @irep = irep
      @steps_per_cycle = steps_per_cycle
    end

    # EM レジスタ初期化用の KV スクリプトを生成
    def generate
      lines = []
      lines << "' ======================================="
      lines << "' mruby/c VM - Memory Initialization"
      lines << "' Generated by RubyOnPlc plc_codegen.rb"
      lines << "' ======================================="
      lines << ""

      lines.concat(generate_vm_state)
      lines << ""
      lines.concat(generate_bytecode)
      lines << ""
      lines.concat(generate_pool)

      lines.join("\n")
    end

    # メモリイメージを Hash として返す (シミュレータ用)
    # { address => value, ... }
    def memory_image
      image = {}

      # VM 状態
      image[PC_ADDR] = 0
      image[STATUS_ADDR] = VM_RUNNING
      image[ERROR_ADDR] = 0
      image[STEP_COUNT_ADDR] = 0
      image[STEP_COUNT_ADDR + 1] = 0
      image[STEPS_PER_CYCLE] = @steps_per_cycle
      image[BYTECODE_LEN_ADDR] = @irep.ilen
      image[NREGS_ADDR] = @irep.nregs
      image[NLOCALS_ADDR] = @irep.nlocals

      # バイトコード
      @irep.instructions.each_byte.each_with_index do |b, i|
        image[BYTECODE_BASE + i] = b
      end

      # 定数プール
      @irep.pool.each_with_index do |entry, i|
        addr = POOL_BASE + i * 2
        case entry.type
        when :int32
          lo = entry.value & 0xFFFF
          hi = (entry.value >> 16) & 0xFFFF
          image[addr] = lo
          image[addr + 1] = hi
        when :int64
          # 下位32ビットのみ使用
          val = entry.value & 0xFFFFFFFF
          lo = val & 0xFFFF
          hi = (val >> 16) & 0xFFFF
          image[addr] = lo
          image[addr + 1] = hi
        end
      end

      # レジスタファイル初期化 (全て0)
      @irep.nregs.times do |i|
        addr = REG_FILE_BASE + i * 2
        image[addr] = 0
        image[addr + 1] = 0
      end

      image
    end

    private

    def generate_vm_state
      lines = []
      lines << "' --- VM State ---"
      lines << "#{MemoryMap.device(PC_ADDR)} = 0           ' PC = 0"
      lines << "#{MemoryMap.device(STATUS_ADDR)} = #{VM_RUNNING}           ' STATUS = running"
      lines << "#{MemoryMap.device(ERROR_ADDR)} = 0           ' ERROR = none"
      lines << "#{MemoryMap.device_long(STEP_COUNT_ADDR)} = 0     ' STEP_COUNT = 0"
      lines << "#{MemoryMap.device(STEPS_PER_CYCLE)} = #{@steps_per_cycle}          ' STEPS_PER_CYCLE"
      lines << "#{MemoryMap.device(BYTECODE_LEN_ADDR)} = #{@irep.ilen}         ' BYTECODE_LEN"
      lines << "#{MemoryMap.device(NREGS_ADDR)} = #{@irep.nregs}          ' NREGS"
      lines << "#{MemoryMap.device(NLOCALS_ADDR)} = #{@irep.nlocals}          ' NLOCALS"
      lines << ""
      lines << "' --- Clear Register File ---"
      lines << "FOR Z1 = #{REG_FILE_BASE} TO #{REG_FILE_BASE + @irep.nregs * 2 - 1}"
      lines << "    #{MemoryMap::DEVICE_NAME}[Z1] = 0"
      lines << "NEXT"
      lines
    end

    def generate_bytecode
      lines = []
      lines << "' --- Bytecode (#{@irep.ilen} bytes) ---"

      @irep.instructions.each_byte.each_with_index do |b, i|
        lines << "#{MemoryMap.device(BYTECODE_BASE + i)} = #{b}"
      end

      lines
    end

    def generate_pool
      return [] if @irep.pool.empty?

      lines = []
      lines << "' --- Constant Pool (#{@irep.pool.size} entries) ---"

      @irep.pool.each_with_index do |entry, i|
        addr = POOL_BASE + i * 2
        case entry.type
        when :int32, :int64
          lines << "#{MemoryMap.device_long(addr)} = #{entry.value}    ' Pool[#{i}]"
        when :float
          lines << "' Pool[#{i}] = #{entry.value} (float - not supported in milestone 1)"
        else
          lines << "' Pool[#{i}] = #{entry} (type #{entry.type} - not supported)"
        end
      end

      lines
    end
  end
end

# コマンドラインから実行した場合
if __FILE__ == $0
  require_relative "mrb_parser"

  if ARGV.empty?
    puts "Usage: ruby plc_codegen.rb <file.mrb>"
    exit 1
  end

  data = File.binread(ARGV[0])
  parser = RubyOnPlc::MrbParser.new(data).parse
  codegen = RubyOnPlc::PlcCodegen.new(parser.irep)
  puts codegen.generate
end
