# frozen_string_literal: true

# PLC コードジェネレータ
# 解析済み IREP から KV スクリプト用のメモリ初期化コードを生成します。

require_relative "mrb_parser"
require_relative "vm_constants"
require_relative "memory_layout"
require "plc_access"

module FaRuby
  # 生成対象がメモリ配置に収まらない場合に発生
  class CodegenError < StandardError; end

  class PlcCodegen
    include VmConstants

    attr_reader :layout

    def initialize(irep, steps_per_cycle: 50, layout: MemoryLayout.default)
      @irep = irep
      @steps_per_cycle = steps_per_cycle
      @layout = layout
    end

    # irep を並べ、それぞれの領域内の位置を決めたもの
    #
    # メソッドを定義すると本体が子 irep になります。バイトコード・定数プール・
    # シンボル表は全 irep で 1 つの領域を分け合い、各 irep の位置を IREP
    # テーブルに入れて実行時に引きます。
    #
    # 並びは **幅優先**です。こうすると同じ親の子が連続するため、親の
    # 「最初の子の番号」に `OP_METHOD` のオペランド (親から見た子の番号) を
    # 足すだけで通し番号になります。深さ優先では子が離れて足し算できません。
    def irep_entries
      @irep_entries ||= build_irep_entries
    end

    # 各領域が上限を超えていないか検証する
    # 超えたまま生成すると隣接領域 (定数プール → シンボル表等) を
    # 破壊するため、生成前に必ず呼ぶ。
    def validate!
      list = irep_entries.map { |e| e[:irep] }
      check_limit("irep の数", list.size, layout.max_ireps)
      check_limit("レジスタ数", list.map(&:nregs).max, layout.max_regs)
      check_limit("バイトコード長", list.sum(&:ilen), layout.max_bytecode)
      check_limit("定数プールのエントリ数", list.sum { |i| i.pool.size }, layout.max_pool)
      check_limit("シンボル数", list.sum { |i| i.symbols.size }, layout.max_symbols)
      self
    end

    # EM レジスタ初期化用の KV スクリプトを生成
    def generate
      validate!
      lines = []
      lines << "' ======================================="
      lines << "' faRuby VM - Memory Initialization"
      lines << "' Generated by faRuby plc_codegen.rb"
      lines << "' ======================================="
      lines << ""

      lines.concat(generate_vm_state)
      lines << ""
      lines.concat(generate_irep_table)
      lines << ""
      lines.concat(generate_bytecode)
      lines << ""
      lines.concat(generate_pool)
      lines << ""
      lines.concat(generate_device_table)
      lines << ""
      lines.concat(generate_method_table_clear)

      lines.join("\n")
    end

    # 可変領域 (EM) のイメージを Hash で返す
    # { address => value, ... }
    def memory_image
      validate!
      image = {}
      top = irep_entries.first

      # VM 状態
      image[layout.pc_addr] = 0
      image[layout.status_addr] = VM_RUNNING
      image[layout.error_addr] = 0
      image[layout.step_count_addr] = 0
      image[layout.step_count_addr + 1] = 0
      image[layout.steps_per_cycle_addr] = @steps_per_cycle
      image[layout.nlocals_addr] = @irep.nlocals
      image[layout.num_ireps_addr] = irep_entries.size
      image[layout.frame_sp_addr] = 0
      image[layout.call_argc_addr] = 0
      image[layout.reg_base_addr] = layout.offset_of(layout.reg_file_base)
      image[layout.irep_table_addr_addr] = layout.irep_table_base
      image[layout.num_symbols_addr] = irep_entries.sum { |e| e[:irep].symbols.size }

      # メソッド表 (ユーザー定義メソッド ID => 本体の irep 番号)
      # 登録は OP_DEF が実行時に行うため、ここでは未定義で埋める
      layout.max_methods.times { |id| image[layout.method_table_addr(id)] = METHOD_UNDEFINED }
      # 実行はトップレベルの irep から始まる
      current_irep_state(top).each { |addr, value| image[addr] = value }

      # レジスタスタック初期化 (スロット全体を 0 = TT_EMPTY + 値 0)
      layout.max_regs.times do |i|
        slot = layout.reg_slot_addr(i)
        SLOT_WORDS.times { |w| image[slot + w] = 0 }
      end

      # 汎用グローバル変数のスロットを 0 初期化する
      device_mappings.select { |m| m[:general] }.each do |m|
        slot = m[:z_offset] - SLOT_VALUE_OFFSET
        SLOT_WORDS.times { |w| image[slot + w] = 0 }
      end

      image
    end

    # 固定領域 (FM) のイメージを Hash で返す
    #
    # アドレスは FM のもの。ホストから書き込むときは ZF の絶対アドレスに
    # 直す必要があります (layout.fixed_host_addr)。
    def fixed_image
      validate!
      image = {}

      irep_entries.each do |entry|
        irep_table_words(entry).each { |addr, value| image[addr] = value }

        entry[:irep].instructions.each_byte.each_with_index do |b, i|
          image[entry[:bytecode_base] + i] = b
        end

        # 定数プール (値スロット: 型タグ + 32ビット値)
        #
        # 未対応の型はスロットを 0 (TT_EMPTY) で埋める。OP_LOADL はタグごと
        # 複製するため、書かずに残すと不定のタグを拾ってしまう。
        entry[:irep].pool.each_with_index do |pool_entry, i|
          value = pool_slot_value(pool_entry)
          addr = entry[:pool_base] + i * SLOT_WORDS + SLOT_VALUE_OFFSET
          image[entry[:pool_base] + i * SLOT_WORDS + SLOT_TYPE_OFFSET] =
            value ? pool_type_tag(pool_entry) : TT_EMPTY
          image[addr]     = value ? value & 0xFFFF : 0
          image[addr + 1] = value ? (value >> 16) & 0xFFFF : 0
        end
      end

      # シンボル表
      device_mappings.each do |m|
        image[m[:table_addr] + DEVICE_TABLE_KIND_OFFSET] = m[:kind]
        if m[:kind] == SYMBOL_KIND_METHOD
          image[m[:table_addr]]     = m[:method_code]
          image[m[:table_addr] + 1] = m[:method_id]
          image[m[:table_addr] + 2] = m[:argc]
          next
        end

        image[m[:table_addr]]     = m[:device_type]
        image[m[:table_addr] + 1] = m[:z_offset]
        image[m[:table_addr] + 2] = m[:access_type] || ACCESS_BIT
      end

      image
    end

    # IREP テーブル 1 エントリ分の { アドレス => 値 }
    #
    # 位置は FM の絶対アドレス。FM は 0-32767 なので Z にそのまま載る。
    def irep_table_words(entry)
      addr = layout.irep_table_addr(entry[:index])
      {
        addr + MemoryLayout::IREP_BYTECODE     => entry[:bytecode_base],
        addr + MemoryLayout::IREP_BYTECODE_LEN => entry[:irep].ilen,
        addr + MemoryLayout::IREP_POOL         => entry[:pool_base],
        addr + MemoryLayout::IREP_SYMBOLS      => entry[:symbol_base],
        addr + MemoryLayout::IREP_NREGS        => entry[:irep].nregs,
        addr + MemoryLayout::IREP_FIRST_CHILD  => entry[:first_child],
      }
    end

    # 実行中の irep を表す VM 状態の { アドレス => 値 }
    #
    # 命令ごとに IREP テーブルを引くとスキャンタイムが延びるため、
    # 切り替え時にここへ写して使う。位置は FM の絶対アドレス。
    def current_irep_state(entry)
      {
        layout.cur_irep_addr     => entry[:index],
        layout.cur_bytecode_addr => entry[:bytecode_base],
        layout.bytecode_len_addr => entry[:irep].ilen,
        layout.cur_pool_addr     => entry[:pool_base],
        layout.cur_symbols_addr  => entry[:symbol_base],
        layout.nregs_addr        => entry[:irep].nregs,
      }
    end

    # シンボルごとの割り当てを解決する
    #
    # シンボル表は irep ごとに別で、番号も irep ごとに振り直されます。全 irep 分を
    # 1 つの領域に詰め、各 irep の先頭を IREP テーブルに入れます。同じ名前が
    # 複数の irep に現れると別のエントリになりますが、解決結果は同じです。
    #
    # シンボル表にはグローバル変数名とメソッド名が混在します。`$` で始まる
    # ものがグローバル変数で、デバイス名にマッチすれば該当デバイスへ、
    # しなければ ($foo 等) 汎用グローバル領域へ出現順に割り当てます。
    # **同じ名前は irep をまたいでも同じスロットを指します** (Ruby の
    # グローバル変数はどこから見ても同じ変数のため)。
    # それ以外はメソッド名として番号に解決します。
    #
    # z_offset は「値ワード」のアドレス (シンボル表に格納する値)。
    def device_mappings
      @device_mappings ||= begin
        slots = {}
        method_ids = {}
        irep_entries.flat_map do |entry|
          entry[:irep].symbols.each_with_index.map do |sym, idx|
            symbol_mapping(sym, entry[:symbol_base] + idx * DEVICE_TABLE_STRIDE,
                           idx, slots, method_ids)
          end
        end
      end
    end

    # ユーザー定義メソッド名 => ID (1 から)
    def method_ids
      device_mappings
        .select { |m| m[:kind] == SYMBOL_KIND_METHOD && m[:method_id] != METHOD_ID_NONE }
        .to_h { |m| [m[:symbol], m[:method_id]] }
    end

    # シンボル 1 つ分の割り当て
    #   slots      汎用グローバルの名前 => アドレス
    #   method_ids ユーザー定義メソッド名 => ID
    def symbol_mapping(sym, table_addr, idx, slots, method_ids)
      parsed = parse_device_symbol(sym) || self.class.parse_device_family(sym)
      if parsed
        { symbol: sym, index: idx, table_addr: table_addr, general: false,
          kind: parsed[:family] ? SYMBOL_KIND_FAMILY : SYMBOL_KIND_VALUE,
          device_type: parsed[:device_type], device_name: parsed[:device_name],
          address: parsed[:address], z_offset: parsed[:z_offset],
          access_type: parsed[:access_type], bit: parsed[:bit],
          family: parsed[:family] || false }
      elsif sym.start_with?("$")
        # 汎用グローバル変数は Ruby の値を保持するので常に32ビット
        value_addr = (slots[sym] ||= layout.general_global_addr(slots.size))
        { symbol: sym, index: idx, table_addr: table_addr, general: true,
          kind: SYMBOL_KIND_VALUE,
          device_type: DEVICE_TYPE_EM, device_name: layout.device_name,
          address: value_addr.to_s, z_offset: value_addr,
          access_type: ACCESS_L, bit: false }
      else
        code, argc = BUILTIN_METHODS.fetch(sym, [METHOD_NONE, 0])
        # 組み込みに無い名前には 1 から通し番号を振る。シンボル表は irep ごとに
        # 別なので、番号を挟まないと同じメソッドに行き着かない
        id = code == METHOD_NONE ? (method_ids[sym] ||= method_ids.size + 1) : METHOD_ID_NONE
        { symbol: sym, index: idx, table_addr: table_addr, general: false,
          kind: SYMBOL_KIND_METHOD, method_code: code, argc: argc, method_id: id }
      end
    end

    private

    def check_limit(label, actual, limit)
      return if actual <= limit

      raise CodegenError, "#{label}が上限を超えています (#{actual} > #{limit})"
    end

    # 幅優先に並べ、領域内の位置を先頭から詰めて決める
    def build_irep_entries
      entries = [{ irep: @irep }]
      index = 0
      while index < entries.size
        entries[index][:first_child] = entries.size
        entries.concat(entries[index][:irep].children.map { |child| { irep: child } })
        index += 1
      end

      bytecode = pool = symbols = 0
      entries.each_with_index do |entry, i|
        entry[:index]         = i
        entry[:bytecode_base] = layout.bytecode_base + bytecode
        entry[:pool_base]     = layout.pool_base + pool * SLOT_WORDS
        entry[:symbol_base]   = layout.device_table_base + symbols * DEVICE_TABLE_STRIDE
        bytecode += entry[:irep].ilen
        pool     += entry[:irep].pool.size
        symbols  += entry[:irep].symbols.size
      end
      entries
    end

    # プールエントリの型タグを返す
    def pool_type_tag(entry)
      case entry.type
      when :int32, :int64 then TT_INTEGER
      when :float         then TT_FLOAT
      else                     TT_EMPTY
      end
    end

    # プールエントリの 32ビット値を返す (未対応の型は nil)
    #
    # 実数は IEEE754 単精度のビット列として格納します。PLC 側は値ワードを
    # .F で読むため、ビット列がそのまま実数として解釈されます。
    def pool_slot_value(entry)
      case entry.type
      when :int32 then entry.value
      when :int64 then entry.value & 0xFFFFFFFF  # 下位32ビットのみ使用
      when :float then float_bits(entry.value)
      end
    end

    # 倍精度の Ruby Float を単精度のビット列にする
    def float_bits(value) = [value].pack("e").unpack1("V")

    def generate_vm_state
      top = irep_entries.first
      lines = []
      lines << "' --- VM State ---"
      lines << "#{layout.device(layout.pc_addr)} = 0           ' PC = 0"
      lines << "#{layout.device(layout.status_addr)} = #{VM_RUNNING}           ' STATUS = running"
      lines << "#{layout.device(layout.error_addr)} = 0           ' ERROR = none"
      lines << "#{layout.device_long(layout.step_count_addr)} = 0     ' STEP_COUNT = 0"
      lines << "#{layout.device(layout.steps_per_cycle_addr)} = #{@steps_per_cycle}          ' STEPS_PER_CYCLE"
      lines << "#{layout.device(layout.nlocals_addr)} = #{@irep.nlocals}          ' NLOCALS"
      lines << "#{layout.device(layout.reset_req_addr)} = 0          ' RESET_REQ = off"
      lines << "#{layout.device(layout.num_ireps_addr)} = #{irep_entries.size}          ' NUM_IREPS"
      lines << "#{layout.device(layout.frame_sp_addr)} = 0          ' FRAME_SP = トップレベル"
      lines << "#{layout.device(layout.reg_base_addr)} = #{layout.offset_of(layout.reg_file_base)}" \
               "          ' REG_BASE"
      lines << ""
      lines << "' --- Current IREP (実行はトップレベルの irep から始まる) ---"
      lines.concat(current_irep_state(top).map { |addr, value| "#{layout.device(addr)} = #{value}" })
      lines << ""
      lines << "' --- Clear Register Stack (#{SLOT_WORDS} words/slot) ---"
      lines << "FOR Z1 = #{layout.reg_file_base} TO #{layout.reg_slot_addr(layout.max_regs) - 1}"
      lines << "    #{layout.device_name}0:Z1 = 0"
      lines << "NEXT"
      lines
    end

    # IREP テーブル。バイトコード・定数プール・シンボル表の位置を irep ごとに持つ
    def generate_irep_table
      lines = ["' --- IREP Table (#{irep_entries.size} ireps) ---"]
      irep_entries.each do |entry|
        lines << "' irep #{entry[:index]}: ilen=#{entry[:irep].ilen} " \
                 "pool=#{entry[:irep].pool.size} syms=#{entry[:irep].symbols.size} " \
                 "nregs=#{entry[:irep].nregs} children=#{entry[:irep].children.size}"
        lines.concat(irep_table_words(entry).map { |addr, value| "#{layout.fixed_device(addr)} = #{value}" })
      end
      lines
    end

    def generate_bytecode
      lines = []
      irep_entries.each do |entry|
        lines << "' --- Bytecode: irep #{entry[:index]} (#{entry[:irep].ilen} bytes) ---"
        entry[:irep].instructions.each_byte.each_with_index do |b, i|
          lines << "#{layout.fixed_device(entry[:bytecode_base] + i)} = #{b}"
        end
      end
      lines
    end

    def generate_pool
      lines = []
      irep_entries.each do |entry|
        next if entry[:irep].pool.empty?

        lines << "' --- Constant Pool: irep #{entry[:index]} (#{entry[:irep].pool.size} entries) ---"
        entry[:irep].pool.each_with_index do |pool_entry, i|
          lines.concat(pool_entry_lines(entry, pool_entry, i))
        end
      end
      lines
    end

    def pool_entry_lines(entry, pool_entry, index)
      slot = entry[:pool_base] + index * SLOT_WORDS
      type_addr  = layout.fixed_device(slot + SLOT_TYPE_OFFSET)
      value_addr = slot + SLOT_VALUE_OFFSET
      label = "Pool[#{index}]"

      case pool_entry.type
      when :int32, :int64
        ["#{type_addr} = #{TT_INTEGER}    ' #{label} type=integer",
         "#{layout.fixed_device_long(value_addr)} = #{pool_entry.value}    ' #{label}"]
      when :float
        bits = float_bits(pool_entry.value)
        ["#{type_addr} = #{TT_FLOAT}    ' #{label} type=float",
         "#{layout.fixed_device(value_addr)} = #{bits & 0xFFFF}    ' #{label} = #{pool_entry.value} (IEEE754 下位)",
         "#{layout.fixed_device(value_addr + 1)} = #{(bits >> 16) & 0xFFFF}    " \
         "' #{label} = #{pool_entry.value} (IEEE754 上位)"]
      else
        ["' #{label} = #{pool_entry} (type #{pool_entry.type} - not supported)"]
      end
    end

    def generate_device_table
      symbol_count = irep_entries.sum { |e| e[:irep].symbols.size }
      return [] if symbol_count.zero?

      lines = []
      lines << "' --- Symbol Table (#{symbol_count} symbols, #{irep_entries.size} ireps) ---"
      lines << "#{layout.device(layout.num_symbols_addr)} = #{symbol_count}    ' NUM_SYMBOLS"

      mappings = device_mappings
      mappings.each do |m|
        table_addr = m[:table_addr]
        if m[:kind] == SYMBOL_KIND_METHOD
          lines.concat(method_table_lines(m))
          next
        end

        kind = ACCESS_NAMES[m[:access_type] || ACCESS_BIT]
        if m[:general]
          lines << "#{layout.fixed_device(table_addr)} = #{DEVICE_TYPE_EM}    ' #{m[:symbol]} type=EM (auto)"
          lines << "#{layout.fixed_device(table_addr + 1)} = #{m[:z_offset]}    ' #{m[:symbol]} -> #{layout.device(m[:z_offset])}"
        else
          lines << "#{layout.fixed_device(table_addr)} = #{m[:device_type]}    ' #{m[:symbol]} type=#{DEVICE_TYPE_NAMES[m[:device_type]]}"
          lines << "#{layout.fixed_device(table_addr + 1)} = #{m[:z_offset]}    ' #{m[:symbol]} Z offset"
        end
        lines << "#{layout.fixed_device(table_addr + 2)} = #{m[:access_type] || ACCESS_BIT}    ' #{m[:symbol]} access=#{kind}"
        family_note = m[:family] ? "デバイス族 (添字でアドレスを決める)" : "-"
        lines << "#{layout.fixed_device(table_addr + DEVICE_TABLE_KIND_OFFSET)} = #{m[:kind]}    " \
                 "' #{m[:symbol]} #{family_note}"
      end

      lines.concat(generate_general_global_clear(mappings))
      lines
    end

    # メソッド名のエントリ。VM は名前ではなく番号で振り分ける
    def method_table_lines(mapping)
      addr = mapping[:table_addr]
      note = mapping[:method_code] == METHOD_NONE ? "ユーザー定義" : "組み込みメソッド"
      [
        "#{layout.fixed_device(addr)} = #{mapping[:method_code]}    ' #{mapping[:symbol]} #{note}",
        "#{layout.fixed_device(addr + 1)} = #{mapping[:method_id]}    ' #{mapping[:symbol]} ユーザー定義ID",
        "#{layout.fixed_device(addr + 2)} = #{mapping[:argc]}    ' #{mapping[:symbol]} 引数の数",
        "#{layout.fixed_device(addr + DEVICE_TABLE_KIND_OFFSET)} = #{SYMBOL_KIND_METHOD}    ' #{mapping[:symbol]} メソッド名",
      ]
    end

    # メソッド表を未定義で埋める。登録は OP_DEF が実行時に行う
    def generate_method_table_clear
      ["' --- Clear Method Table (#{layout.max_methods} entries) ---",
       "FOR Z1 = #{layout.method_table_base} TO #{layout.method_table_base + layout.max_methods - 1}",
       "    #{layout.device_name}0:Z1 = #{METHOD_UNDEFINED}",
       "NEXT"]
    end

    # 汎用グローバル変数のスロットを 0 初期化する
    # (memory_image と同じ初期化を KV スクリプト側でも行う)
    def generate_general_global_clear(mappings)
      # 同じ名前が複数の irep に現れると同じスロットを指すため重複する
      slots = mappings.select { |m| m[:general] }.map { |m| m[:z_offset] }.uniq
      return [] if slots.empty?

      # 汎用グローバルは汎用グローバル領域の先頭から連続して割り当てられる
      first = slots.min - SLOT_VALUE_OFFSET
      last  = slots.max - SLOT_VALUE_OFFSET + SLOT_WORDS - 1

      ["",
       "' --- Clear General Globals (#{slots.size} slots × #{SLOT_WORDS} words) ---",
       "FOR Z1 = #{first} TO #{last}",
       "    EM0:Z1 = 0",
       "NEXT"]
    end

    # アクセス幅サフィックス。アンダースコアで区切ってもよい
    #
    # 16進アドレスを持つ B では `$B1F` が「0x1F」なのか「0x1 を実数で」なのか
    # 区別できないため、区切りたいときに `$B1_F` と書けるようにしています。
    # 10進アドレスのデバイスでは元々曖昧さがなく、読みやすさのためだけです。
    SUFFIX = "_?([SULDF]?)"

    # ワードデバイス: 10進アドレス + アクセス幅 (省略時は16ビット符号付き)
    #   $DM100 / $DM100L / $DM100_L
    #
    # 略記 (E, D, M) は正式名より後ろに置く。正規表現の選択肢は左から順に
    # 試されるため、$EM100 が E + "M100" と読まれないようにするため
    WORD_DEVICE_PATTERN      = /^\$(EM|DM|ZF|E|D)(\d+)#{SUFFIX}$/i
    WORD_DEVICE_PATTERN_BARE = /^(EM|DM|ZF|E|D)(\d+)#{SUFFIX}$/i

    # ビットデバイス: サフィックス無しなら個別ビット、付ければ整数
    #   $MR100 は接点、$MR100L はそこから32ビット、$T0D はタイマ現在値
    #
    # アドレスの基数がデバイスで違うためパターンを分けます。
    #   B      16進。D と F は数字でもありサフィックスでもあるため、
    #          アドレスを貪欲に取る ($B1F は 0x1F)。区切るなら $B1_F
    #   その他 10進。D や F はアドレスに現れないので曖昧さなし ($T0D は T0 + D)
    #
    # CR はインデックス扱い不可のため非対応
    # MR を R と M より、LR を L より先にマッチさせる
    HEX_BIT_DEVICE_PATTERN       = /^\$(B)([0-9A-Fa-f]+)#{SUFFIX}$/i
    HEX_BIT_DEVICE_PATTERN_BARE  = /^(B)([0-9A-Fa-f]+)#{SUFFIX}$/i
    BIT_DEVICE_PATTERN           = /^\$(MR|R|LR|L|M|T|C)(\d+)#{SUFFIX}$/i
    BIT_DEVICE_PATTERN_BARE      = /^(MR|R|LR|L|M|T|C)(\d+)#{SUFFIX}$/i

    # デバイス族: アドレスを持たない形。添字を付けて実行時にアドレスを決める
    #   $DM[100 + i]    16ビット符号付き (既定)
    #   $DML[100 + i]   32ビット符号付き
    #   $MR[64 + i]     ビットデバイス
    #
    # 略記の D / E / M があるため、正式名を先に試して一意に解析します。
    # $DML は DM + L、$DL は D (= DM) + L です。
    #
    # 添字は「デバイス番号」です。ワードデバイスは表示上のアドレスと一致
    # しますが、MR / R / B は一致しません (MR400 は番号 64、B10 は 16)。
    # 番号空間では線形で、MR415 の次は MR500 になります。
    WORD_FAMILY_PATTERN = /^\$(EM|DM|ZF|E|D)#{SUFFIX}$/i
    BIT_FAMILY_PATTERN  = /^\$(MR|R|B|LR|L|M|T|C)#{SUFFIX}$/i

    # タイマ・カウンタは実数を扱えない (KV Studio の変換が通らない)
    NO_FLOAT_DEVICE_TYPES = [DEVICE_TYPE_T, DEVICE_TYPE_C].freeze
    # KV が受け付ける略記。正式名に正規化してから先へ渡します。
    #
    # ラダーでは略記で入力すると正式名に変換されます。plc_access は略記を
    # 知らないため、正規化しないと **別のデバイスになります**。
    # たとえば LR100 は番号 16 (MR や R と同じチャンネル・ビット形式) ですが、
    # plc_access は "L100" も受け付けてしまい番号 100 を返します。
    PROTOCOL_DEVICE_NAME = {
      "L" => "LR", "M" => "MR", "D" => "DM", "E" => "EM",
    }.freeze

    def self.protocol_name(device_name)
      PROTOCOL_DEVICE_NAME.fetch(device_name, device_name)
    end

    # 正式名のみ。略記は protocol_name を通してから引くこと
    DEVICE_NAME_TO_TYPE = {
      "EM" => DEVICE_TYPE_EM, "DM" => DEVICE_TYPE_DM, "ZF" => DEVICE_TYPE_ZF,
      "R" => DEVICE_TYPE_R, "MR" => DEVICE_TYPE_MR, "B" => DEVICE_TYPE_B,
      "LR" => DEVICE_TYPE_L,
      "T" => DEVICE_TYPE_T, "C" => DEVICE_TYPE_C,
    }.freeze
    DEVICE_TYPE_NAMES = DEVICE_NAME_TO_TYPE.invert.freeze

    # KvDevice を使ってデバイスアドレスの Z レジスタ用オフセットを取得
    # HEXDEC (R, MR, LR 等): MR200 → 32, R100 → 16, LR100 → 16
    # HEX (B): B10 → 16
    # DEC (EM, DM 等): そのまま
    #
    # 名前は必ず protocol_name を通したものを渡すこと。plc_access は略記を
    # 知らず、"L100" を受け付けても番号 100 を返して LR100 (番号 16) と食い違う。
    def self.device_z_offset(device_name, addr_str)
      PlcAccess::Protocol::Keyence::KvDevice.new("#{protocol_name(device_name)}#{addr_str}").number
    end

    def parse_device_symbol(sym)
      self.class.parse_device_symbol(sym)
    end

    # シンボル名 ($DM100, $DM100L) からデバイス情報をパース
    # address:     元のアドレス (PLC アダプタ通信用)
    # z_offset:    Z レジスタ用オフセット (マッピングテーブル・シミュレータ用)
    # access_type: ACCESS_* (ビットデバイスは nil)
    def self.parse_device_symbol(sym)
      parse_device(sym, WORD_DEVICE_PATTERN, HEX_BIT_DEVICE_PATTERN, BIT_DEVICE_PATTERN)
    end

    # デバイス名 (DM100, DM100L, $ なし) からデバイス情報をパース
    def self.parse_device_name(name)
      parse_device(name, WORD_DEVICE_PATTERN_BARE,
                   HEX_BIT_DEVICE_PATTERN_BARE, BIT_DEVICE_PATTERN_BARE)
    end

    # デバイス族 ($DM, $DML, $MR 等) をパースする。該当しなければ nil
    #
    # アドレスを持たないため z_offset は 0 で、添字を足して実行時に決めます。
    def self.parse_device_family(sym)
      return nil unless sym

      if (m = sym.match(WORD_FAMILY_PATTERN))
        device_name = protocol_name(m[1].upcase)
        return { device_type: DEVICE_NAME_TO_TYPE[device_name], address: "0",
                 z_offset: 0, device_name: device_name, family: true,
                 access_type: VmConstants::ACCESS_SUFFIXES.fetch(m[2].to_s.upcase), bit: false }
      end

      return nil unless (m = sym.match(BIT_FAMILY_PATTERN))

      device_name = protocol_name(m[1].upcase)
      device_type = DEVICE_NAME_TO_TYPE[device_name]
      bit = m[2].to_s.empty?
      access_type = bit ? nil : VmConstants::ACCESS_SUFFIXES.fetch(m[2].to_s.upcase)
      check_float_support(device_name, device_type, access_type)

      { device_type: device_type, address: "0", z_offset: 0,
        device_name: device_name, family: true, bit: bit, access_type: access_type }
    end

    # ワードデバイス → ビットデバイス (16進 → 10進) の順にマッチを試みる
    #
    # ビットデバイスは幅サフィックスの有無で意味が変わります。
    #   無し  個別ビット (true / false)
    #   有り  そのビットから連続したビット列を整数として (MR, R, B, L)
    #         タイマ・カウンタの現在値 (T, C)
    def self.parse_device(str, word_pattern, hex_bit_pattern, bit_pattern)
      return nil unless str

      if (m = str.match(word_pattern))
        return build_device(m, bit: false)
      end

      m = str.match(hex_bit_pattern) || str.match(bit_pattern)
      return nil unless m

      # サフィックスが付いていればワードとして扱う
      build_device(m, bit: m[3].to_s.empty?)
    end

    def self.build_device(match, bit:)
      # ホストと通信する名前へ正規化する ($L100 も $LR100 も LR100)
      device_name = protocol_name(match[1].upcase)
      addr_str = match[2]
      device_type = DEVICE_NAME_TO_TYPE[device_name]
      access_type = bit ? nil : VmConstants::ACCESS_SUFFIXES.fetch(match[3].to_s.upcase)
      check_float_support(device_name, device_type, access_type)

      { device_type: device_type, address: addr_str,
        z_offset: device_z_offset(device_name, addr_str),
        device_name: device_name, bit: bit, access_type: access_type }
    end

    # タイマ・カウンタは実数を扱えない (KV Studio の変換が通らない)。
    # 幅を付けると現在値を返すデバイスなので、実数の出番が無い。
    def self.check_float_support(device_name, device_type, access_type)
      return unless access_type == VmConstants::ACCESS_F
      return unless NO_FLOAT_DEVICE_TYPES.include?(device_type)

      raise CodegenError,
            "#{device_name} は実数 (F サフィックス) を扱えません。" \
            "幅を付けると現在値を返すため、整数の幅を指定してください (#{device_name}0D 等)"
    end
  end
end

# コマンドラインから実行した場合
if __FILE__ == $0
  require_relative "mrb_parser"

  if ARGV.empty?
    puts "Usage: ruby plc_codegen.rb <file.mrb>"
    exit 1
  end

  data = File.binread(ARGV[0])
  parser = FaRuby::MrbParser.new(data).parse
  codegen = FaRuby::PlcCodegen.new(parser.irep)
  puts codegen.generate
end
